Word:
  type: entity
  id:
    id:
      column: id
      type: int
  table: word
  fields:
    name:
      type: string
    meaning:
      type: string
    synonyms:
      type: string
    classification:
      type: text
